
-- DATABASE SCRIPTS TO CREATE DATABASE
-- ///// THERE IS ALREADY A DATABASE SET UP WITH THE TABLES ON YOUR SERVER SO YOU WILL NOT NEED THESE

CREATE DATABASE SWCS344;

CREATE TABLE user (
    userID int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username TINYTEXT NOT NULL,
    email TINYTEXT NOT NULL,
    pwd LONGTEXT NOT NULL
);

CREATE TABLE info (
    entryID int(11) NOT NULL AUTO_INCREMENT,
    userID int(11) NOT NULL,
    entryear int(11) NOT NULL,
    entrymonth int(11) NOT NULL,
    entryday int(11) NOT NULL,
    hoursslept int(11) NOT NULL,

);

